# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PracticeMVVMRxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxDataSources', '~> 3.0'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxAlamofire'
    pod 'Kingfisher', '~> 5.0'
  # Pods for PracticeMVVMRxSwift

  target 'PracticeMVVMRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
