# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PracticeRxswift1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "RxSwift"
pod "RxCocoa"

  # Pods for PracticeRxswift1

  target 'PracticeRxswift1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
